export const ASTNodeType = {
  PROGRAM: "PROGRAM",

  VARIABLE_DECLARATION: "VARIABLE_DECLARATION",

  BINARY_EXPRESSION: "BINARY_EXPRESSION",

  IDENTIFIER: "IDENTIFIER",

  CHAR_LITERAL: "CHAR_LITERAL",
  BOOLEAN_LITERAL: "BOOLEAN_LITERAL",
  NUMERIC_LITERAL: "NUMERIC_LITERAL",

  NULL_LITERAL: "NULL_LITERAL",
} as const;

export type ASTNodeType = (typeof ASTNodeType)[keyof typeof ASTNodeType];
