export const AST_NODE_TYPES = [
  "PROGRAM",

  "VARIABLE_DECLARATION",
  "INPUT_STATEMENT",
  "OUTPUT_STATEMENT",
  "CODE_BLOCK",

  "IF_STATEMENT",
  "FOR_LOOP",

  "ASSIGNMENT_EXPRESSION",
  "BINARY_EXPRESSION",

  "IDENTIFIER",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "BOOLEAN_LITERAL",
  "NUMERIC_LITERAL",
  "NULL_LITERAL",
] as const;
