export const TokenType = {
  START_BLOCK: "START_BLOCK",
  END_BLOCK: "END_BLOCK",
  CONDITIONAL_BLOCK: "CONDITIONAL_BLOCK",

  NEWLINE: "NEWLINE",

  VARIABLE_DECLARATION: "VARIABLE_DECLARATION",
  IDENTIFIER: "IDENTIFIER",

  INPUT_STATEMENTS: "INPUT_STATEMENTS",
  OUTPUT_STATEMENTS: "OUTPUT_STATEMENTS",

  FOR_LOOP: "FOR_LOOP",

  OPEN_PARENTHESIS: "OPEN_PARENTHESIS",
  CLOSE_PARENTHESIS: "CLOSE_PARENTHESIS",

  ESCAPED_CHAR: "ESCAPED_CHAR",

  LOGICAL_OPERATOR: "LOGICAL_OPERATOR",
  ARITHMETIC_OPERATOR: "ARITHMETIC_OPERATOR",
  ASSIGNMENT_OPERATOR: "ASSIGNMENT_OPERATOR",

  AMPERSAND: "AMPERSAND",
  COMMA: "COMMA",
  CARRIAGE_RETURN: "CARRIAGE_RETURN",
  COLON: "COLON",

  STRING: "STRING",

  BOOLEAN_LITERAL: "BOOLEAN_LITERAL",
  WHOLE_NUMERIC_LITERAL: "WHOLE_NUMERIC_LITERAL",
  DECIMAL_NUMERIC_LITERAL: "DECIMAL_NUMERIC_LITERAL",
  CHAR_LITERAL: "CHAR_LITERAL",

  DATATYPE: "DATATYPE",
  NULL: "NULL",

  EOF: "EOF",
} as const;

export type TokenType = (typeof TokenType)[keyof typeof TokenType];
