export const TokenType = {
  START_BLOCK: "START_BLOCK",
  END_BLOCK: "END_BLOCK",
  CONDITIONAL_BLOCK: "CONDITIONAL_BLOCK",

  NEWLINE: "NEWLINE",

  VARIABLE_DECLARATION: "VARIABLE_DECLARATION",
  IDENTIFIER: "IDENTIFIER",

  INPUT_STATEMENTS: "INPUT_STATEMENTS",
  OUTPUT_STATEMENTS: "OUTPUT_STATEMENTS",

  FOR_LOOP: "FOR_LOOP",

  EQUALS: "EQUALS",

  OPEN_PARENTHESIS: "OPEN_PARENTHESIS",
  CLOSE_PARENTHESIS: "CLOSE_PARENTHESIS",

  ESCAPED_CHAR: "ESCAPED_CHAR",

  LOGICAL_OPERATOR: "LOGICAL_OPERATOR",
  ARITHMETIC_OPERATOR: "ARITHMETIC_OPERATOR",
  ASSIGNMENT_OPERATOR: "ASSIGNMENT_OPERATOR",

  BOOLEAN_VALUE: "BOOLEAN_VALUE",

  AMPERSAND: "AMPERSAND",
  COMMA: "COMMA",
  CARRIAGE_RETURN: "CARRIAGE_RETURN",
  COLON: "COLON",

  STRING: "STRING",
  NUMERIC_LITERAL: "NUMERIC_LITERAL",

  DATATYPE: "DATATYPE",
} as const;

export type TokenType = (typeof TokenType)[keyof typeof TokenType];
